# Generated by Django 4.0.2 on 2022-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
